members:
- aanm
- bmcustodio
- borkmann
- brb
- gandro
- gentoo-root
- glibsm
- jibi
- joestringer
- kaworu
- kkourt
- michi-covalent
- nathanjsweet
- nebril
- pchaigno
- qmonnet
- rolinh
- sayboras
- thorn3r
- tklauser
- vadorovsky
- willfindlay
- tommyp1ckles
